sudo: false
language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.6

# Install steps MUST succeed or will immediately halt the build.
install:
  - nvm install 12.18.3
  - node -v
  - pip install flake8
  - pip install -r requirements.txt
  - npm install

# Script steps, if erroring, will fail the build but not stop the build process.
# This is useful because we want to know that linting is broken, but it shouldn't
# stop us from testing/linting/compiling other things as well.
script:
  - flake8 --statistics --show-source --disable-noqa
  - npm run build
  - npm run lint
  - nosetests
